permalink: /:categories/:title 

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

title: Amber
tagline: cryptogrAmber Sandbox
author:
  name: Amber Fechko
  email: a@cryptogramber.com
  github: cryptogramber
    
production_url: https://cryptogramber.github.io

contentlist:
  - title: updates
    url: /updates/
